def generate_ci_report(run: dict, baseline: dict | None = None) -> str:
    """Generate a GitHub-flavored markdown report from a run result."""
    report = run.get("report", {})
    passed = report.get("passed", 0)
    failed = report.get("failed", 0)
    regressed = report.get("regressed", 0)
    total = report.get("total", 0)
    eval_results = report.get("eval_results", {})

    lines = [
        "## TraceGrade Eval Report",
        "",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Passed | {passed} |",
        f"| Failed | {failed} |",
        f"| Regressed | {regressed} |",
        f"| Total | {total} |",
        "",
    ]

    if regressed > 0:
        lines.append(f"**{regressed} regression(s) detected**")
        lines.append("")

    if eval_results:
        lines.append("### Eval Results")
        lines.append("")
        lines.append("| Eval | Status | Score | Details |")
        lines.append("|------|--------|-------|---------|")

        for eval_id, result in eval_results.items():
            name = result.get("name", eval_id)
            status = "PASS" if result.get("passed") else "FAIL"
            if result.get("regression"):
                status = "REGRESSED"
            score = f"{result.get('score', 0):.2f}"
            details = result.get("details", "")[:80]

            emoji = {"PASS": "✅", "FAIL": "❌", "REGRESSED": "⚠️"}.get(status, "")
            lines.append(f"| {name} | {emoji} {status} | {score} | {details} |")

    lines.append("")
    lines.append("---")
    lines.append("Generated by [TraceGrade](https://github.com/tracegrade/tracegrade)")

    return "\n".join(lines)
